allowBuilds:
  esbuild: true
overrides:
  '@excalidraw/excalidraw>nanoid': 3.3.16
  '@excalidraw/mermaid-to-excalidraw>nanoid': 5.1.5
  lodash-es: 4.18.1
minimumReleaseAgeExclude:
  - '@astrojs/internal-helpers@0.10.2'
  - '@astrojs/markdown-satteri@0.3.5'
  - '@astrojs/react@6.0.2'
  - astro@7.1.5
