x-local-backend: &local-backend
  image: interview-studio-backend:local

services:
  backend:
    <<: *local-backend
    build:
      context: ../..
      dockerfile: deployment/docker/backend.Dockerfile
      args:
        FRONTEND_STAGE: frontend-build
  migrate:
    <<: *local-backend
  fixtures:
    <<: *local-backend
  port-check:
    <<: *local-backend
  backup:
    <<: *local-backend
  restore:
    <<: *local-backend
